### ISSUE TITLE
React: localhost is running on port 9000 but cypress try to connect on port 8080

### ISSUE THREAD

**Issue by flcarre** [jhipster/jhipster-lite#1320]
While i'm running e2e test via cypress, tests failed cause my app server is running on port 9000 as defined in vite.config.ts and cypress baseUrl is on port 8080 as defined in cypress-config.json

**Comment by pascalgrimaud** [comment]
@flcarre : in JHipster projects (generator-jhipster and here too), the use of cypress is a real E2E tests, it's not component tests. For that, we already have jest, which is enough.
That's why you need to really start the application: ./mvnw spring-boot:run and then, run e2e test with Cypress

This part was refactor by @Bolo89 recently to make it common for all fronts

**Comment by flcarre** [comment]
ok sorry i wasn't up to date ^^'

**Comment by flcarre** [comment]
In my mind, run cypress only in the complete application make it much harder to test and debug

**Comment by pascalgrimaud** [comment]
Closing this, as the behavior is explained
