### ISSUE TITLE
Add a cli to jhipster-lite

### ISSUE THREAD

**Issue by antarus** [jhipster/jhipster-lite#2345]
Having a cli in addition to the front can be useful for different use cases.

I made a first version trying to manage the dynamic side of the new api/module.

Not knowing, if it could interest you, I put it here (https://github.com/antarus/jhicli) while waiting for your feedback.

I took the opportunity to discover picoli and try to respect DDD concepts and hexagonal architecture.

I am therefore interested in all comments, even the unpleasant ones :D

**Comment by pascalgrimaud** [comment]
Thanks a lot for taking this initiative!
I already discussed with Julien about it, few months ago as he already implemented it there: https://github.com/microsoft/NubesGen

I'll try to find time to test it and give you some feedback ;)

**Comment by pascalgrimaud** [comment]
I don't forget, I'll do my best to try this ;)

**Comment by pascalgrimaud** [comment]
So I gave it a try yesterday and it works very well. Very good job @antarus 

I have a few comments for improving it, but it's not important now. I can adress it later if needed

The important discussion here is what to do next?

For using jhcli, you need to start the backend, then I think it's easier to open the browser than using the terminal, but it's just my opinion. In which case it would be better to use the cli, rather than the browser?

What could be done:
- include this project to this one, separate into 2 maven modules. It will imply to be at 100% and respect the architecture. Need to rework the CI and release workflow too. I think it's too earlier and it will give more work. I'd prefer to focus on feature (front in jhlite, vuejs, react, etc)
- include the project to jhipster orga in a separate project as once it's stable, it won't need to have the same lifecycle of jhlite release. Am I correct ? You'll be the lead of this, of course
- do nothing for now and let the project in your account, so once jhlite is more popular, we can rethink of it

Again, thanks a lot for your work.
Tell me what you think too, it's important @antarus

**Comment by antarus** [comment]
Hello,
indeed you have to launch the backend. I started with the idea of just making a client other than the browser.
eventually I think that with a little redesign, it could be integrated in order to avoid launching the backend then the cli.

in the possible options:
the first is actually the most expensive.
for the second, the cli can have a different lifecycle as long as the api/module doesn't actually change.

on my side, at the moment, I'm more interested in the jdl import😄 so we can go with option 3.

**Comment by pascalgrimaud** [comment]
For now, I'm very happy with the UI, so not sure a CLI is needed here, as it will require more maintenance
I'd like to have this project as much as simple
Of course, the CLI project can be a community project, or under the JHipster organization and you could be the main developer on this @antarus 

What do you think?
I'm closing this ticket, don't hesitate to comment if you disagree, @antarus
