### ISSUE TITLE
Suggestion on jhipster lite design

### ISSUE THREAD

**Issue by Tcharl** [jhipster/jhipster-lite#2446]
Hi experts, how are you?

First, I wanted to thank you for that wonderful initiative (and the demo), that will bring new breath and way more compared to the current platform.

Here are some few architectural recommendations to avoid some traps and ensure the perenity of that new stack. please consider them, they come from years of development experience.

# Use third party dependencies as much as you can
Try to avoid generating stuff as much as you can and try to componentize

## Backend

Try to follow the spring boot principles for configuration classes
  - Create a configuration annotated with `@Conditional`whenever you want it to be contextual (i.e. jhipster-spring-boot-undertow)
  - Create a starter module referencing a bunch of related dependencies (i.e. the [undertow starter](https://github.com/spring-projects/spring-boot/tree/main/spring-boot-project/spring-boot-starters/spring-boot-starter-undertow)

So that the generator will mostly tweak the gradle build file or pom in order to add or remove features for everything that is not related to business code.

### Contract vs impl

 Split APIs (method signature), SPI (service on which you can contribute) and implementation: the absence of decoupling the contracts and the impls are really painful (it will avoid the current issue we have with the 'generator-base.js' file which is quite annoying. 

## Frontend

Same principle applies to frontend with npm dependencies.
For example, I guess that the admin console (or each part of it) could be implemented as a webcomponent (one library for all) or an implementation by language (last resort).

Side advantage of this approach: libraries will be reusable in the original platform and the lite one :-).

# Modules

## Independent modules.

The DDD/Hexagonal approach is pretty good and smart, but implementing it as a package is limiting. Prefer hosting each bounded context in its dedicated maven module: it will bring contributivity for free and help newcomers bootstrap.
You can also rely on maven archetype to ease new module creation. I don't need to tell that you'll also be able to release plugin independently and so on...

Note that it won't make the release process more cumbersome: you can use the maven release plugin on the parent to release everything at once.

## Use state machine and events to improve the developer experience.

A good combination of HATEOAS, events (spring events I guess) and state machine could help to create the developer path to creating a cohesive application, be sure to to save the current state somewhere (in a .yo-rc.json file ^^).

# Modeling

The API approach is awesome, still, Jhipster is in fine a dsl and should also rely on state of the art modeling techniques

## Best practices

Usually, modeling approach is split into some layers:

 - The reasonable default, which help the users to get some options that are the most commonly used (just offer a 'choose for me' option to go to the current state.
 - A Metamodel (a spec to persist the model) which is today the contract to persist the entity.json and the .yo-rc contract)
 - A model: on the current jh version you have the generated entity.json and the .yo-rc file: I you could keep it like this, you'll have everything on top for free (options, jdl)
 - One or more Visual specific modeler (textual dsl, UML-like class diagrams, forms, cli, studio ...) to let the user fill his model, the Jdl and the api are the target I guess: sticking to the current metamodel will bring it for free, at least until we have both platforms GA.

Thank you for your reading, I hope that you'll keep some of this advice in mind while implementing the future of the community. On our side, we'll continue to maintain the current generator until this framework will bring the same critical features (entities :-p). Eager to switch to a generator made with Java!

Cheers

**Comment by DamnClin** [comment]
A little update on that, first here we are (on main): 

* Most modules have been migrated (only svelte remains  but no blocking point on that), we now have 84 modules on JHLite;
* The landscape (a map / graph) of modules made it to the frontpage allowing easier applications of the "good" modules.

There is a still a lot of work to do, of course (ex: https://github.com/jhipster/jhipster-lite/issues/3045) BUT we probably have reach an important millstone.

**For the "generate code" VS "depend on lib",** in fact that depends a lots on modules! Some modules depends a lot on lib, others only generate code and I think that's totally OK that way as the goal of JHLite is to allow experts in a given field to contribute modules.

Ex: the `application-service-hexagonal-architecture-documentation` generate a documentation on how to make one flavor of hexagonal architecture. This can't really be in a dependency / published page since the goal is to bootstrap something and allow people to adapt that to there needs.

**For the API contract splitting** for now we don't really have contract to the external world, that will probably happen when we'll build something to allow organization to have their own module deployed (and that will probably come in multiple forms, we'll see).

**For the "split project as maven modules"** in fact I don't like it and only had bad experiences with that since it make any refactoring more complicated. BUT this may be just me, I have no strong position on that.

**For the "save the state"**, we are generating a file in the project that track the applied modules and the properties used. This is also used to load the application applied modules and used properties when selecting a path in the app. BUT this is not implemented with a state machine (that may be a mistake).

If you can take some time to start the project from main and tell us if that make any sense that would be great.

**Comment by pascalgrimaud** [comment]
Closing this one as no answer from @Tcharl and I agree with all points from @DamnClin 

Feel free to comment and discuss if needed

**Comment by Tcharl** [comment]
Thank you for your consideration and your answer.
Fully satisfied, keep up the great job experts!
