### ISSUE TITLE
Migrate / refactor users

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2482]
The users (src/main/java/tech/jhipster/lite/generator/server/springboot/user) seems to be very important for many JHipster users but also comes with a lot of problems.

Do we just migrate it or do we take time to totally rethink that (probably with a user / account separation going in the direction started in OAuth2 account)? Any advice?

**Comment by pascalgrimaud** [comment]
I'd prefer to rethink it, because the user domain should be common between different database: mysql, psql, mongodb, etc...

**Comment by DamnClin** [comment]
So, following our discussions on https://github.com/jhipster/jhipster-lite/issues/2612 what's the goal of this?

If it is to have a working example of a changeset and persistence I think we should really base that on the dummy feature.

My concern here is: I really don't want to promote local accounts management as I think this is, in 99% cases, a mistake (the % left: you are coding keycloak / cognito / and IDP). 

Local user management is ok but, most of the time, you don't want to manage your user authentication in the app, you want some business related information for your users.

@pascalgrimaud @Bolo89 @DanielFran @MSaguer  you contributed to users entity or changelog at some point. What is your usage of those?

**Comment by DamnClin** [comment]
After some discussion out of github we are taking the direction to remove that and use dummy as an example. @pascalgrimaud I think we should remove the bounty from this one

**Comment by pascalgrimaud** [comment]
Yes, let's remove user, which is related to JWT
The default option for security in JH Lite is OAuth2

The reason is, there are too much features to implement to make the whole JWT feature completed:
- entities User and Authority for all existing databases
- jpa repository for all databases
- link between security and the repository
- workflow to register a new user
- workflow for forgot password
- etc

Too much work for a system which is probably less used than OAuth2
