### ISSUE TITLE
Add GraalVM support for JHipster Lite

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#2819]

**Comment by pascalgrimaud** [comment]
Increasing the bounty to motivate people as it's a good feature to have

**Comment by atomfrede** [comment]
I will have a fresh look with  boot 3 on main branch.

**Comment by atomfrede** [comment]
Short status update, I got the compilation up and running, right now fighting with reflection issues, but it looks the configuration can be done. Will keep you updated. Can't tell if the jgit config works as I don't come to that point right now.

**Comment by pascalgrimaud** [comment]
Good news @atomfrede :-)

**Comment by atomfrede** [comment]
So far so good. I have fixed the configuration for (some) parts of jackson serialization and the git stuff seems to work too. Still have some issues with xml processing and modification. Will try to fix them step by step, but the applied patches look good although an error occurs

**Comment by atomfrede** [comment]
It seems there is only one or two issues left.

* Applying the maven module results in a null pointer when executed as native executable, can't tell why. Applying a bunch of other modules (e.g. mongo, neo, angular) worked just fine even with git commit 
* The landscape view is not displayed because of a javascript error (which confuses me totally why thats the case)
* Swagger UI results in 404
