### ISSUE TITLE
Rework page loading

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3005]
Loading pages now just display a "Loading" text which is not good and comes with a blinking effect when changing page, adding placeholder during loading may be a good idea

**Comment by swarajsaaj** [comment]
The blinking effect is mainly due to anchor `href` which is causing the page to reload on each header click.
https://github.com/jhipster/jhipster-lite/blob/6d2317c1572001783f225ce004edcc38b8b6f30b/src/main/webapp/app/common/primary/header/Header.vue#L14

Will provide a PR for this small fix of blinking effect.

I have added a plain css loader as in https://cssloaders.github.io/, but the issue can be kept open till actual placeholders are implemented, something like https://www.npmjs.com/package/placeholder-loading

**Comment by swarajsaaj** [comment]
@pascalgrimaud this issue should be reopened as #3868 only partially fixes the issue
