### ISSUE TITLE
Auto-deploy the project

### ISSUE THREAD

**Issue by nishit93-hub** [jhipster/jhipster-lite#3388]
Hi,
 
Can we auto-deploy the project after generating the code instead of downloading it? Does Jhipster have an auto-deployment feature?

**Comment by pascalgrimaud** [comment]
I don't understand what you mean with 'auto deploy'.

How did you use JHipster Lite?
- locally ?
- https://lite.jhipster.tech ?

Where do you want to deploy ?
- AWS ? GAE ? Azure ? Heroku ? Etc.

**Comment by nishit93-hub** [comment]
Hi,

I have deployed Jhipster on GCP VM.

Now whenever I create a new project with required patches or modules, I have to manually download the project and run it.

With Auto-deployment I meant, Is there any way I can directly deploy the project somewhere after applying the patches or modules instead of downloading it?

**Comment by DamnClin** [comment]
The "download" button is mainly here for the instance deployed [here](https://lite.jhipster.tech) (we should probably remove that from the local instance...). When starting locally (`./mvnw`) you can set your project folder in the folder path to get all the already applied configuration to your project and directly update in on your local disk.

I don't really see a point in having a deploy button in the interface since JHlite goal is not to generate full applications, this is not a no-code platform. The goal here is to generate some infrastructure code when building a business application.

For me, updates should go though a normal CI / CD pipeline, that mean: 

* Create a branch;
* Make the update;
* Push it;
* Review it;
* Merge it and that will be deployed.

(You can do that without branches and push to trunk the that will be the same :))

**Comment by pascalgrimaud** [comment]
Closing this one, following the last comment
