### ISSUE TITLE
Default value for module properties

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3480]
We should switch "example" to "default" in module properties and use that to valuate fields if no user input can be found

**Comment by swarajsaaj** [comment]
Maybe `defaultValue` as `default` conflicts with the Java keyword.

**Comment by swarajsaaj** [comment]
@DamnClin @pascalgrimaud 
Need your suggestion here regarding the filling of default values in fields, what should be trigger to valuate empty fields:-
- First option is to fill the default values whenever clicking on a module (landscape or patch):-
   - This is good for new project usecases, so that new values are always prefilled.
   - This may be annoying for user if he wants to enter existing project path afterwards as current logic does not override already filled values (default values in this case)
- Second option is to fill the default values on path change (blur):-
   - This is good for existing projects where the values can be filled as per existing project
   - This makes default values useless as an already generated project will have most of values (its only good for new modules being applied/patched).

**Comment by DamnClin** [comment]
Thinking about it I don't think it is a good idea to actually "fill" the fields. I think we should just use the default value when validating for fields that are not valuated by the users. 

Filling the field will be annoying since users will have to delete the value before adding it again.

**Comment by swarajsaaj** [comment]
@DamnClin Yes I made the change locally and tried it, did not feel very elegant on UX.
Did you mean to allow users to Apply modules even with empty mandatory properties and use default value in backend for generation?

**Comment by DamnClin** [comment]
> Did you mean to allow users to Apply modules even with empty mandatory properties and use default value in backend for generation?

Yep

**Comment by pascalgrimaud** [comment]
Adding a bounty on this great feature
Don't forget to claim it @swarajsaaj 

Thanks @DamnClin for the review

**Comment by swarajsaaj** [comment]
Thanks @pascalgrimaud and @DamnClin 
claimed the bounty here https://opencollective.com/generator-jhipster/expenses/100676

**Comment by pascalgrimaud** [comment]
@swarajsaaj : approved
