### ISSUE TITLE
Move technical exception to dedicated package

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3684]
As in https://github.com/jhipster/jhipster-lite/pull/3682 move this package in generated applications (in ZalandoProblemsModuleFactory)

**Comment by pascalgrimaud** [comment]
@DamnClin : I wonder if we could add a new optional property like 'packageDestination', so the user can choose where to generate these classes.
By default, it could be:
- error.infrastructure.primary

Then, the user could choose the old one for exemple:
- technical.infrastructure.primary.exception

It means, the template should look like:

```
package {{packageName}}.{{packageDestination}};
```

I think it could be nice because:
- some user don't like `infrastructure`
- some other could replace primary by something else
- etc
- 
What do you think?

**Comment by DamnClin** [comment]
This mean adding, at least, 3 properties, could be done but not sure the UX will be that good

**Comment by pascalgrimaud** [comment]
Let's wait few days and think about my suggestion, as maybe there can be some impact

**Comment by murdos** [comment]
@DamnClin : `ZalandoProblemsModuleFactory` doesn't exist anymore. Is this issue still relevant since migration to Spring Boot 3?

**Comment by pascalgrimaud** [comment]
let's close this as it's probably not relevant anymore
