### ISSUE TITLE
Allow CSS refresh without having to do mvn clean

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3779]
With the css management update you need to clean and restart the server to see css updates (same using vite), this is really annoying. cc @Gnuk

**Comment by Gnuk** [comment]
I think there is two features behind this:

- Launch tikui + vite in dev mode and add proxy to vite to have the tikui served style instead of JHipster served style
- Change maven configuration to accept build even if it's not clean

About the second point:  I don't really know and have an idea on how to do it and I also don't know if it's the same behavior with vite build for the webapp (need to check).

I may do the first one but I'll be glad to let someone else to do the other one.
