### ISSUE TITLE
Add versions files paths in module creation documentation

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3959]
As suggested in https://github.com/jhipster/jhipster-lite/pull/3950#issuecomment-1278705066

**Comment by niranjanib** [comment]
Hi @DamnClin , I would to pick up this issue :) 

I read the referenced comment and from what I understand we need to add the path in the module-creation.md so that the place to add dependency versions whenever a module is created is more explicit. 

By file paths, do you mean referencing each of the file/folder managing different dependencies? 
For example, adding the filepath for the pom.xml, Dockerfile etc separately in the documentation, because at the moment all of them reside in the same package.

**Comment by DamnClin** [comment]
Hello,

It's easier than that :). In src/main/resources/generator/dependencies there are different files handling dependencies for different tools (docker, maven, ...). We just need to document each of this file content.

Those files are used to get the latest version of dependencies and are updated by dependabot (so we don't manage versions by hand)

**Comment by niranjanib** [comment]
Ah okay, thank you :) 

Will work on it 👍

**Comment by DamnClin** [comment]
If you want to make this a little bit more challenging you can have a look at how those files are used to resolve versions in JHLite :D. (I'm actually using that for tech interviews :D)

**Comment by murdos** [comment]
Already fixed with #4176
