### ISSUE TITLE
Migrate landscape css to tikui

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3970]
The landscape css partly remains in the .vue file. Should be put in tikui

**Comment by Gnuk** [comment]
Sorry, I'm a bit late to answer because i'm busy this week until monday.

I just want to say that I'm currently on this migration but with a different approach, by creating small components and by composing them using atomic design. (That's why there is some atoms already presents).

My other approach is to make a light theme instead of the dark theme (you can see it's not dark in the pattern library)

I'm also working with @ascelineboullen for this, that's also why I've not started the past week.

Sure we need help about style, maybe it could be interesting to make less coupled issues (maybe some smaller issues to design existing components with the design from Asceline also).

Don't know what you think @pascalgrimaud and @nassimerrahoui (following the PR #4065)?

***

I also link #3969 because the style is similar for some parts.

The main issue to fallow all of this are on #2894

**Comment by nassimerrahoui** [comment]
> Sorry, I'm a bit late to answer because i'm busy this week until monday.
> 
> I just want to say that I'm currently on this migration but with a different approach, by creating small components and by composing them using atomic design. (That's why there is some atoms already presents).
> 
> My other approach is to make a light theme instead of the dark theme (you can see it's not dark in the pattern library)
> 
> I'm also working with @ascelineboullen for this, that's also why I've not started the past week.
> 
> Sure we need help about style, maybe it could be interesting to make less coupled issues (maybe some smaller issues to design existing components with the design from Asceline also).
> 
> Don't know what you think @pascalgrimaud and @nassimerrahoui (following the PR #4065)?
> 
> I also link #3969 because the style is similar for some parts.
> 
> The main issue to fallow all of this are on #2894

I haven't started the ticket too much so I can close my PR

**Comment by renanfranca** [comment]
There isn't css at .vue file. Should it be close?

**Comment by pascalgrimaud** [comment]
Maybe it's done, let's close this
