### ISSUE TITLE
Delete the typescript module?

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3979]
The typescript module was intended to build simple projects for kata but I don't think this is really interesting no. @Gnuk @pascalgrimaud do we delete it?

**Comment by pascalgrimaud** [comment]
And it is not tested in the CI
I think we can delete it, let's wait @Gnuk's advices

**Comment by Gnuk** [comment]
Yes, we can I think.

**Comment by pascalgrimaud** [comment]
Following https://github.com/jhipster/jhipster-lite/issues/4057 and https://github.com/jhipster/jhipster-lite/pull/4058

What do you think about this @hdurix ?
Should we keep this module? We could totally keep it, as it doesn't require any maintenance since months, and if it's the case, it's easy to maintain it

**Comment by hdurix** [comment]
I don't get it. Why removing it? Indeed this is nice for kata in JS environment

**Comment by pascalgrimaud** [comment]
Ok then so let's keep this, as it doesn't impact any other module for now
