### ISSUE TITLE
feature request - users want to customize mustache template

### ISSUE THREAD

**Issue by jhcao23** [jhipster/jhipster-lite#411]
sometimes developers want to provide their customized mustache template they prefer but they don't wanna override the existing jhipster-lite src code. I hope there is a way for dev users to input the path to the customized template from the cli, for example, `jhipster-lite-cli-command ... --override-mustache-template SecurityConfiguration.java.mustache=SOME_LOCAL_FILE_PATH`.

if this is through API calls interaction:
1. need an API endpoint for GET request and return mutache template content
2. find a way to allow POST API to upload a customized mustache template (with a simply validation) to generate their code

**Comment by pascalgrimaud** [comment]
This is a possibility provided by [generator-jhipster](https://github.com/jhipster/generator-jhipster) -> see the full documentation at https://www.jhipster.tech/modules/creating-a-blueprint/

But in my opinion, this approach makes the generator-jhipster really complex, and hard to maintain, because it needed to be sync with generator-jhipster -> https://www.jhipster.tech/modules/official-blueprints/
Very few official blueprints are sync with v7.

In JHipster Lite, the approach is totally different, as you'll generate step by step only what you want.

I don't think providing this possibility you suggested, is the right direction for this project as it will bring a big complexity which is not necessary.

So your use case is to have your own SecurityConfiguration.java file, instead of the one provided by JHipster Lite. For that, you have different solutions:

Solution 1:
- init project with JHipster Lite, add Maven, add Java Base
- add Spring Boot, add Tomcat
- instead of adding Security JWT, **code it yourself**, don't use the Security API to generate these files

If you're not happy with the provided files, it's easy to make the choice to not use the API.

Solution 2:
- init project with JHipster Lite, add Maven, add Java Base
- add Spring Boot, add Tomcat
- add Security JWT, and edit the file you want, so edit your SecurityConfiguration with your own version

This solution is the best in my opinion, as it's quick.

Solution 3:
- fork the project
- create a new context and code the generation part your want, by using templates provided by JHipster Lite and your own templates
- as it's in a new context, you won't have any conflict when rebasing against upstream main branch

**Comment by jhcao23** [comment]
Thank you @pascalgrimaud! I think I gave a bad example - should be "controller/service/repository". But Solution 3 is definitely a good option if we want to keep jhipster-lite simple - the only drawback is the forked new repo would need to keep updating by pulling from upstream whenever there is a new feature/version published from upstream. What I really mean is something like [Shadowing in Gatsby Themes](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/), however, again, at this moment and the early stage of LIte, we can ignore it for now.

**Comment by pascalgrimaud** [comment]
@jhcao23 : another possibility is to publish jhipster-lite as a library, so you could use it as a Maven Dependency. You'll have all the template engine with mustache

**Comment by pascalgrimaud** [comment]
yes, we are in a very early stage. We need to :
- add more options
- add at least 1 front framework
- build a front, to call different APIs, instead of using Swagger

Then, we can add docs to help users to fork / use JHipster Lite as library, as the current structure / architecture of generator can still completely change

**Comment by jhcao23** [comment]
looking forward and willing to contribute whenever possible!
