### ISSUE TITLE
Changed package name does not delete old package

### ISSUE THREAD

**Issue by biergit** [jhipster/jhipster-lite#4194]
Using the UI to create a Spring Boot app and then changing the package name in the UI followed by "Apply selected" and "Download" results in a zip-File containing old and new package.
It's also not clear how to completely start a fresh composition from the UI. 
Clicking on "Patches" then back to "Landscape" seems to do that but then the "Properties" are no longer filled with default values.

**Comment by DamnClin** [comment]
The described behavior looks really logical to me. I don't see how we can keep the possibility to come back to an existing project without that... Maybe blocking edition in that case but that would delete the feature of keeping properties when changing package

**Comment by atomfrede** [comment]
As long as the old package is empty that sounds okay to me. Starting a fresh composition can be achieved by using another path, such that the project is generated into an empty folder (I think).

**Comment by biergit** [comment]
@atomfrede I see no way to deselect previously applied modules without either restarting the whole service or clicking on "Patches" then back to "Landscape".

When I start and select up to "java-base" - apply selected - download - select up to "spring-boot-tomcat" - change "packageName", "projectName" and "baseName" - apply selected - download then I get two different packages with content.

Also I think providing at least a tooltip to "Apply selected" and "Apply new" would be quite helpful. I still have not figured out the difference :D

**Comment by DamnClin** [comment]
@biergit You are using the online version or a local version? In fact, download is only for online version, useless locally which is the normal usage of JHLite.

You can't "unapply" from the UI since it does not make any sense, you can unapply using git by deleting or  reverting the module commit.

If you want to start a new project change the path so you'll start without any applied module on a fresh folder. When changing path the applied modules will be refreshed from your project (so you can add modules to an existing project).

Apply new apply the newly selected (not yet applied) modules
Apply selected apply all selected modules (reapplying already applied modules). The number of modules that will be applied is displayed in the button.

**Comment by biergit** [comment]
@DamnClin thanks that helped. I was using the Docker container locally.

**Comment by DamnClin** [comment]
For me this is totally intended, closing but don't hesitate to repoen if I missed something
