### ISSUE TITLE
Security: update CORS configuration

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#621]
Following this https://github.com/jhipster/jhipster-lite/pull/620, the CORS configuration should be updated:
- in comment by default in application.properties
- uncommented in application-local.properties

This config should be added here too: https://github.com/jhipster/generator-jhipster/pull/17683/files

**Comment by beatfreaker** [comment]
@pascalgrimaud can I work on this ?

If I understand correctly we want to modify
https://github.com/jhipster/jhipster-lite/blob/53e8f6d20a045d0250a570eb9f3462ac109bf188/src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/jwt/domain/JwtSecurityDomainService.java#L144-L156

so that it adds `cors` configuration in both `application.properties` as commented and in `application-local.properties`
today it only adds in `application.properties` file correct ?


Also what you meant be
> This config should be added here too: https://github.com/jhipster/generator-jhipster/pull/17683/files

**Comment by pascalgrimaud** [comment]
Yes exactly what you said
- in application.properties: CORS are commented
- in application-local.properties: CORS are here too and not commented

This additional property should be added too: `allowed-origin-patterns: 'https://*.githubpreview.dev'`
