### ISSUE TITLE
Spring Boot Actuator: security property

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#6942]
Check and verify why we have this property `spring.security.oauth2.client.registration.oidc.scope` in Spring Boot Actuator module:

https://github.com/jhipster/jhipster-lite/blame/main/src/main/java/tech/jhipster/lite/generator/server/springboot/technicaltools/actuator/domain/SpringBootActuatorModuleFactory.java#L29

If it is not needed, it should be removed

**Comment by pascalgrimaud** [comment]
Yes I understand this property
What I mean by creating this ticket is, this property should be added when using oauth2 module, instead of actuator module
So the logic should be moved there

**Comment by Saravana-PS** [comment]
@pascalgrimaud , Yeah, now it's clear. Since  the property `spring.security.oauth2.client.registration.oidc.scope` is available in both the OAuth2 module and the Actuator module, and it is being set with the same values in both places, It is generally safe to remove it from the Actuator module. Can you please assign it on me so that I will implement the change and raise the PR.

**Comment by pascalgrimaud** [comment]
You're awesome, thanks for your contribution :)

**Comment by Saravana-PS** [comment]
Thanks a lot for your support and encouragement :)

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/jhipster-lite/pull/7081
