### ISSUE TITLE
Project Scope/purpose and difference with Jhipster

### ISSUE THREAD

**Issue by yelhouti** [jhipster/jhipster-lite#745]
Hi all,

can anyone explain how this project is different from JHipster, whether we are talking about the scope or the technologies used?

Are there feature in JHipster that we know we don't want here ?

Will this project support generating entities from JDL or json ?

Are users of JHipster expected to switch once this project is mature enough ?

Maybe the README could have a section about all these questions that people already using JHipster would have.

**Comment by pascalgrimaud** [comment]
Hello @yelhouti, I don't know if you saw the long mail in our mailing list. If not, here the story of JHipster Lite: https://groups.google.com/g/jhipster-dev/c/LufZy80i_BQ

About entities:
For the moment, I don't plan to support entities, because when you code in TDD in Hexagonal Architecture, you must not think about entities, but think about domain model and business rules.
Entities can be generated later and you only need the entities and repository. No need service, resource, front etc
So for doing that, the trick is to use generator-jhipster and git clean what I don't need.

About switching, I don't plan to tell users to use JHipster Lite instead. They will if they want, as the generated code is different from generator-jhipster :
- 100% coverage
- 0 code smell
- no duplication
- in Hexagonal Architecture

**Comment by yelhouti** [comment]
@pascalgrimaud no I missed that, thanks for the link.

I also find it very difficult to maintain blueprints with the way the code is done today in jhipster. Hopefully, this approach will be better suited for customization, I like the idea anyway.

I don't fully understand how the hexagonal architecture is supposed to work (how the final code should look like). Hopefully when I have a clearer I could help with something.

Good luck anyways :)

**Comment by pascalgrimaud** [comment]
@yelhouti : I don't know if you're french. If it's the case, you can have a look at https://blog.ippon.fr/2021/02/17/spring-boot-hexagone/

You have an example of generated project with JHipster Lite at: https://github.com/pascalgrimaud/jhlite-sample-app
The dummy context is the perfect example for showing adapters and ports, with a domain model:
- https://github.com/pascalgrimaud/jhlite-sample-app/tree/main/src/main/java/tech/jhipster/beer/dummy

**Comment by pascalgrimaud** [comment]
As I already said, me too I'm totally lost when trying to help in existing blueprints. I don't understand all the process, so I can't imagine for new contributors who would like to code their blueprints...

That's why I say to all my customers: don't code your own blueprint, it's impossible to maintain

**Comment by yelhouti** [comment]
@pascalgrimaud thanks for the links, and yes I can speech french. I "maintain" two blueprints and yes it is a a huge pain every few months I try merge there is a big refactoring :s

**Comment by pascalgrimaud** [comment]
I'll close this ticket as soon as there is an official page, dedicated to JHipster Lite at https://jhipster.tech

**Comment by pascalgrimaud** [comment]
Closing this one, as the page was created: https://www.jhipster.tech/jhipster-lite/
