### ISSUE TITLE
Mongock: adding User and Authority

### ISSUE THREAD

**Issue by juliensadaoui** [jhipster/jhipster-lite#805]
- related at #691
- similar to what was done for Liquibase and Flyway

**Comment by beatfreaker** [comment]
@juliensadaoui are you still working on this ?
If not I can pick it ?

**Comment by pascalgrimaud** [comment]
I think you can @beatfreaker

**Comment by pascalgrimaud** [comment]
I'd prefer to do it in separate pull request
The reason is to can use another framework to do migration, instead of using Mongock

The workflow is:
- init, spring boot, etc...
- add mongodb as database
- create UserEntity and AuthorityEntity for MongoDB (it will be different than for SQL database)
- add Mongock (like in your PR)
- add Mongock migration script for User and Authority

So part 3 and part 5 can be done separately. What do you think ?

**Comment by beatfreaker** [comment]
Yup, sound good, so first I can work on creating UserEntity and AuthorityEntity for MongoDB,
once that is merge will create another PR to add migration script for those two entities

**Comment by pascalgrimaud** [comment]
@beatfreaker : yes, let's create a new ticket first for that ;) can you ?

**Comment by DamnClin** [comment]
As we have decide to remove those users models this is probably unrelevant (but need to make this for the dummy feature)
