### ISSUE TITLE
New module for enabling "local" spring boot profile by default 

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-lite#8475]
Following #8348: the Spring Boot "local" profile should be enabled by default, and disabled explicitly in CI pipelines.

This will allow improving develop experience with a better default configuration for local development.

**Comment by pascalgrimaud** [comment]
Thanks for thinking about this, @murdos 

In my opinion, it needs to be discussed as if we put 'local' profile by default, I afraid it will be similar to generator-jhipster:
- dev -> local
- prod -> no profile

From my experience, dev / prod profile confused the developpers as we need to test both, when coding the application.

That's why, in JHipster Lite, my ideas was:
- no default profile
- local profile: which added some additional stuff like logging level, devtools livereload, etc. And it's not mandatory when coding

So what do you think about adding a module, which will activate 'local' profile by default, so the users who want a better default config, can use it ?

**Comment by murdos** [comment]
I never encountered such confusion, and in my experience dev profile doesn't need to be tested automatically (it's tested manually when developer launches the app and regression for this profile is not critical), while no-profile is tested through automatic tests.

But indeed a dedicated optional model could provide the same feature 😉
